#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

mkdir -p /DATA/htdocs
mkdir -p /DATA/logs/nginx
# start nginx

mkdir -p /tmp/nginx
chown nginx:nginx /tmp/nginx
chown -R nginx:nginx /DATA

exec /usr/sbin/nginx

pushd /DATA/htdocs > /dev/null
exec /usr/sbin/nginx
popd > /dev/null
