#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

# start php-fpm
mkdir -p /DATA/logs/php-fpm

# check if /DATA/bin does not exist
if [ ! -d /DATA/bin ] ; then
  mkdir /DATA/bin
  chown nginx:nginx /DATA/bin
  cp /usr/bin/wp /DATA/bin/wp

  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  chmod +x wp-cli.phar
  mv wp-cli.phar /DATA/bin/wp
fi

# run in the foreground as the nginx user.
s6-setuidgid 100:101 /usr/sbin/php-fpm81 -F